<?php
$db['order']=array(
        
    'columns' =>
        array(
            'id' => array(
                'type' => 'int(10)',
                'pkey' => true,
                'extra' => 'auto_increment',
                'required' => true,
                'label' => '编号',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => false,
                'width' => 60,
                'hidden' => true,
                'order'=>10,
            ),
            'order_id' => array(
                'type' => 'int(11)',
                'default' => '0',
                'required' => true,
                'label' => '订单id',
                'in_list' => false,
                'default_in_list' => false,
            ),
            'order_bn' => array(
                'type' => 'varchar(32)',
                'required' => true,
                'label' => '订单号',
                'searchtype' => 'nequal',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'width' => 160,
                'order'=>20,
            ),
            'type_id' => array(
                'type' => array(
                    0=>'普通发票',
                    1=>'专业发票',
                ),
                'default' => '0',
                'required' => true,
                'label' => '发票类型',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'order'=>30,
                'width' => 80,
            ),
            'amount' => array(
                'type' => 'money',
                'default' => '0',
                'required' => true,
                'label' => '开票金额',
                'filtertype' => 'number',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'order'=>40,
                'width' => 80,
            ),
            'cost_tax' => array(
                'type' => 'money',
                'default' => '0',
                'required' => true,
                'label' => '税金',
                'in_list' => true,
                'default_in_list' => true,
                'order'=>50,
                'width' => 60,
            ),
            'tax_rate' => array(
                'type' => 'tinyint(2)',
                'default' => '0',
                'required' => true,
                'label' => '税率',
                'order'=>52,
                'in_list' => true,
                'default_in_list' => false,
            ),
            'title' => array(
                'type' => 'varchar(150)',
                'label' => '发票抬头',
                'in_list' => true,
                'default_in_list' => true,
                'searchtype' => 'head',
                'filtertype' => 'normal',
                'filterdefault' => false,
                'order'=>25,
                'width'=>200,
            ),
            'is_status' => array(
                'type' => array(
                    0=>'未开票',
                    1=>'已开票',
                ),
                'default' => '0',
                'required' => true,
                'label' => '状态',
                'in_list' => true,
                'default_in_list' => true,
                'order'=> 5,
                'width' => 60,
            ),
            'is_print' => array(
                'type' => array(
                    0=>'否',
                    1=>'是',
                    2=>'作废',
                ),
                'default' => '1',
                'required' => true,
                'label' => '打印',
                'in_list' => true,
                'default_in_list' => true,
                'order'=>55,
                'width' => 50,
            ),            
            'invoice_no' => array(
                'type' => 'char(32)',
                'label' => '发票号',
                'in_list' => true,
                'default_in_list' => false,
            ),
            'content' => array(
                'type' => 'varchar(32)',
                'label' => '发票内容',
                'in_list' => true,
                'order'=>23,
            ),
            'batch_number' => array(
                'type' => 'varchar(100)',
                'label' => '批次号',
                'in_list' => true,
                'default_in_list' => true,
                'searchtype' => 'nequal',
                'filterdefault' => true,
                'order'=>28,
            ),
            'delivery_id' => array(
                'type' => 'int(10)',
                'default' => '0',
                'required' => true,
                'label' => '发货单号',
                'in_list' => false,
                'default_in_list' => false,
            ),
            'remarks' => array(
                'type' => 'text',
                'label' => '发票备注',
                'in_list' => true,
               'default_in_list' => false,
            ),
            'operator' => array(
                'type' => 'mediumint(8)',
                'default' => '0',
                'required' => true,
                'label' => '操作人',
            ),
            'print_num' => array(
                'type' => 'smallint(6)',
                'default' => '0',
                'required' => true,
                'label' => '打印次数',
                'in_list' => true,
                    'default_in_list' => false,
            ),
            'create_time' => array(
                'type' => 'time',
                'default' => '0',
                'label' => '创建日期',
                'filtertype' => 'time',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'width' => 130,
            ),
            'dateline' => array(
                'type' => 'time',
                'default' => '0',
                'label' => '开票日期',
                'filtertype' => 'time',
                'filterdefault' => true,
                'in_list' => true,
                'width' => 130,
            ),
            'print_time' => array(
                'type' => 'int(10)',
                'default' => '0',
                'required' => true,
                'label' => '最后更新',
            ),
            'tax_company' => array(
                'type' => 'varchar(50)',
                'label' => '客户名称',
                'in_list' => true,
                'default_in_list' => false,
            ),
            'ship_area' => array(
                'type' => 'varchar(100)',
                'label' => '客户收货地区',
                'default_in_list' => false,
            ),
            'ship_addr' => array(
                'type' => 'varchar(255)',
                'label' => '客户地址',
                'in_list' => true,
                'default_in_list' => false,
            ),
            'ship_tel' => array(
                'type' => 'char(32)',
                'label' => '客户电话',
                'in_list' => true,
                'default_in_list' => false,
            ),
            'ship_tax' => array(
                'type' => 'varchar(32)',
                'label' => '客户税号',
                'in_list' => true,
                'default_in_list' => false,
            ),
            'ship_bank' => array(
                'type' => 'varchar(32)',
                'label' => '客户开户银行',
                'in_list' => true,
                'default_in_list' => false,
            ),
            'ship_bank_no' => array(
                'type' => 'char(32)',
                'label' => '客户银行账号',
                'in_list' => true,
                'default_in_list' => false
            ),
    ),
    'index' => array(
        'type_status' => array(
            'columns'=>array(
                0=>'type_id',
                1=>'is_status',
            ),
        ),
        'order_id'=>array(
            'columns'=>array(
                0=>'order_id',
            ),
            'prefix'=>'unique',
        ),
        'order_bn'=>array(
            'columns'=>array(
                0=>'order_bn',
            ),
            'prefix' => 'unique',
        ),
    ),
    'comment' => '订单发票表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
);